### ISSUE TITLE
Error being generated in console

### ISSUE THREAD

**Issue by phocks** [meagre/qurious#4]
```
I20150801-17:32:32.651(10)? Exception from sub quotesLatest id gdPfFamfSxzwY636E Error: Match error: Failed Match.OneOf or Match.Optional validation
I20150801-17:32:32.651(10)?     at checkSubtree (packages/check/match.js:244:1)
I20150801-17:32:32.651(10)?     at check (packages/check/match.js:32:1)
I20150801-17:32:32.651(10)?     at [object Object]._.extend._getFindOptions (packages/mongo/collection.js:239:1)
I20150801-17:32:32.651(10)?     at [object Object]._.extend.find (packages/mongo/collection.js:275:1)
I20150801-17:32:32.651(10)?     at [object Object].Meteor.publish.limit [as _handler] (app\main.js:272:19)
I20150801-17:32:32.651(10)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150801-17:32:32.651(10)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:950:1)
I20150801-17:32:32.651(10)?     at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
I20150801-17:32:32.651(10)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp/livedata_server.js:582:1)
I20150801-17:32:32.651(10)?     at packages/ddp/livedata_server.js:546:1
I20150801-17:32:32.651(10)? Sanitized and reported to the client as: Match failed [400]
I20150801-17:32:32.651(10)?
I20150801-17:32:32.682(10)? Exception from sub quotesLatest id rXc5bvRonLjrbZ5mt Error: Match error: Failed Match.OneOf or Match.Optional validation
I20150801-17:32:32.682(10)?     at checkSubtree (packages/check/match.js:244:1)
I20150801-17:32:32.682(10)?     at check (packages/check/match.js:32:1)
I20150801-17:32:32.682(10)?     at [object Object]._.extend._getFindOptions (packages/mongo/collection.js:239:1)
I20150801-17:32:32.682(10)?     at [object Object]._.extend.find (packages/mongo/collection.js:275:1)
I20150801-17:32:32.682(10)?     at [object Object].Meteor.publish.limit [as _handler] (app\main.js:272:19)
I20150801-17:32:32.682(10)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150801-17:32:32.682(10)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:950:1)
I20150801-17:32:32.682(10)?     at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
I20150801-17:32:32.682(10)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp/livedata_server.js:582:1)
I20150801-17:32:32.682(10)?     at packages/ddp/livedata_server.js:546:1
I20150801-17:32:32.682(10)? Sanitized and reported to the client as: Match failed [400]
```

I'm getting this in the console every time I refresh a Latest quotes or Popular quotes etc page....

I think it has something to do with the "Load more" "Infinite scrolling" feature... but I'm not sure.... It doesn't seem to be breaking the site, so I guess it's not totally urgent to fix.

**Comment by phocks** [comment]
I commented out `return Meteor.subscribe('quotesLatest', 5);` in the waitOn function in the route, which I put in there because as it is now it doesn't show the loader animation gif....... will have to keep playing.
